### ISSUE TITLE
ConstanceAdmin should create LogEntry objects

### ISSUE THREAD

**Issue by gavinwahl** [jezdez/django-constance#112] opened 2015-08-17 22:35 UTC
`admin.ModelAdmin` has a method `log_change` to create LogEntry objects to show a history of actions by admins. ConstanceAdmin should do that too.

**Comment by jezdez** [comment] 2015-09-24 10:24
Certainly, even though it's a bit more complicated because constance doesn't itself have model instances by default. Not sure if this could be hacked somehow.

Seems like a duplicate of #19.

**Closed** 2015-09-24 10:51 UTC
